### ISSUE TITLE
Time bug in Google calendar and Microsoft calendars

### ISSUE THREAD

**Issue by CruelPineapple** [Saafo/uestc-coursetable-parser#1]
When importing ics file to Google calendar or Microsoft calendar, time line goes 1 hour earlier than the time stated in the file.
guess it is caused by the VTIMEZONE, which controls the daylight saving time.

**Comment by Saafo** [comment]
@CruelPineapple Thanks for feedback. I'll fix it tonight.

**Comment by Saafo** [comment]
After deleting daylight and rrule in standard, this bug was fixed.
